# Generated by Django 2.1.dev20180206232904 on 2018-03-02 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumtable',
            fields=[
                ('album_id', models.AutoField(primary_key=True, serialize=False)),
                ('album_name', models.CharField(max_length=60)),
                ('album_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ratingtable',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songstable',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=60)),
                ('artist_name', models.CharField(max_length=60)),
                ('view_count', models.IntegerField(default=0)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysongs.Albumtable')),
            ],
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysongs.Songstable'),
        ),
        migrations.AddField(
            model_name='ratingtable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
